version: '3.8'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf
      - ./postgres/schema.sql:/app/schema.sql

  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf

  client:
    restart: unless-stopped
    volumes:
      - ./client:/app

  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/yarn.lock:/app/yarn.lock
    environment:
      - IS_DEV=true
      - APP_NAME='Apple pie🥧'
      - APP_DOMAIN=http://localhost
      - MAILING_ACCOUNT=apple_pie_test@outlook.com
      - MAILING_ACCOUNT_PASSWORD=apple_pie_2700

  nginx:
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./nginx/config:/etc/nginx/conf.d

  v2:
    restart: unless-stopped
    volumes:
      - ./v2:/app
      - ./ssl:/ssl
    environment:
      - IS_DEV=true

  swagger:
    image: swaggerapi/swagger-ui:v3.40.0
    volumes:
      - ./swagger/swagger.yaml:/usr/share/nginx/html/swagger/swagger.yaml
