version: '3.8'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf
      - ./postgres/schema.sql:/app/schema.sql

  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf

  client:
    restart: unless-stopped
    volumes:
      - ./client:/app

  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./server:/app
    environment:
      - IS_DEV=true
      - APP_NAME='Apple🥧pie local'
      - APP_DOMAIN=http://localhost

  nginx:
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/apple_pie_nginx.conf:/etc/nginx/conf.d/apple_pie_nginx.conf
    ports:
      - 80:80
