version: '3.1'

services:
  server:
    container_name: apple_pie_server
    build: ./server
    restart: unless-stopped
    ports:
      - '2700:2700'
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db

  db:
    container_name: apple_pie_db
    build: ./db
    restart: unless-stopped
    volumes:
      - ./db/schema.sql:/app/schema.sql
    ports:
      - '5432:5432'
