version: '3.1'

services:
  nginx:
    container_name: apple_pie_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - server
      - client

  client:
    container_name: apple_pie_client
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    container_name: apple_pie_server
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/yarn.lock:/app/yarn.lock
      - ./server/tsconfig.json:/app/tsconfig.json
      - ./server/.env:/app/.env
      - ./server/.dev.env:/app/.dev.env
      - ./server/swagger.json:/app/swagger.json
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - PGUSER=${POSTGRES_USER}
      - PGHOST=apple_pie_postgres
      - PGDATABASE=${POSTGRES_DB}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SESSION_DB_NUMBER=${REDIS_SESSION_DB_NUMBER}
      - REDIS_CASH_DB_NUMBER=${REDIS_CASH_DB_NUMBER}
      - JWT_AUTH_SECRET_WORD=${JWT_AUTH_SECRET_WORD}
      - JWT_VERIFY_EMAIL_SECRET_WORD=${JWT_VERIFY_EMAIL_SECRET_WORD}
      - SESSION_EXPIRE_TIME=${SESSION_EXPIRE_TIME}
      - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
      - FAKE_USER_EXPIRE_TIME=${FAKE_USER_EXPIRE_TIME}
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: apple_pie_postgres
    build: ./postgres
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf
      - ./postgres/schema.sql:/app/schema.sql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # только для GUI базы
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: apple_pie_redis
    build: ./redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} # только для GUI базы
    volumes:
      - ./redis/redis.conf:/app/redis.conf
