version: '3.8'

services:
  nginx:
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./nginx/config:/etc/nginx/conf.d

  client:
    restart: unless-stopped
    volumes:
      - ./client:/app
    command: npm run start

  server:
    restart: unless-stopped
    volumes:
      - image_hosting:/var/www/images
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/yarn.lock:/app/yarn.lock
      - ./server/swagger.yaml:/app/swagger.yaml
    environment:
      - IS_DEV=true
      - APP_DOMAIN=http://localhost
      - MAILING_ACCOUNT=apple_pie_test@outlook.com
      - MAILING_ACCOUNT_PASSWORD=apple_pie_2700
    command: yarn dev

  postgres:
    restart: unless-stopped
    volumes:
      - ./postgres/postgresql.conf:/app/postgresql.conf
      - ./postgres/schema.sql:/app/schema.sql

  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf
