version: '3.1'

services:
  nginx:
    container_name: apple_pie_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - root_server

  client:
    container_name: apple_pie_client
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - root_server

  root_server:
    container_name: apple_pie_root_server
    build: ./root_server
    restart: unless-stopped
    volumes:
      - ./root_server/src:/app/src
      - ./root_server/package.json:/app/package.json
      - ./root_server/yarn.lock:/app/yarn.lock
      - ./root_server/.env:/app/.env
      - ./root_server/tsconfig.json:/app/tsconfig.json
    environment:
      - APP_PORT=80
      - AUTH_SERVER_DOMAIN=http://apple_pie_auth_server
      - PGUSER=postgres
      - PGHOST=apple_pie_postgres
      - PGDATABASE=postgres
      - PGPASSWORD=2700
      - PGPORT=${PG_PORT}
      - JWT_SECRET_WORD=${JWT_SECRET_WORD}
    depends_on:
      - postgres
      - redis

  auth_server:
    container_name: apple_pie_auth_server
    build: ./auth_server
    restart: unless-stopped
    volumes:
      - ./auth_server/src:/app/src
      - ./auth_server/package.json:/app/package.json
      - ./auth_server/yarn.lock:/app/yarn.lock
      - ./auth_server/.env:/app/.env
    environment:
      - APP_PORT=80
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_NUMBER=0
      - JWT_SECRET_WORD=${JWT_SECRET_WORD}
    depends_on:
      - redis

  postgres:
    container_name: apple_pie_postgres
    build: ./postgres
    restart: unless-stopped
    volumes:
      - ./postgres/schema.sql:/app/schema.sql
    ports:
      - ${PG_PORT}:${PG_PORT} # только для GUI базы
    environment:
      - POSTGRES_PASSWORD=2700

  redis:
    container_name: apple_pie_redis
    build: ./redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} # только для GUI базы
    volumes:
      - ./redis/redis.conf:/app/redis.conf
