version: '3.1'

services:
  nginx:
    container_name: apple_pie_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
        - '80:80'
    volumes:
        - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - server

  db:
    container_name: apple_pie_db
    build: ./db
    restart: unless-stopped
    volumes:
      - ./db/schema.sql:/app/schema.sql
    ports:
      - '5432:5432'

  server:
    container_name: apple_pie_server
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
