version: '3.1'

services:
  nginx:
    container_name: apple_pie_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - server

  client:
    container_name: apple_pie_client
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    container_name: apple_pie_server
    build: ./server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/yarn.lock:/app/yarn.lock
      - ./server/tsconfig.json:/app/tsconfig.json
    environment:
      - APP_PORT=80
      - PGUSER=postgres
      - PGHOST=apple_pie_postgres
      - PGDATABASE=postgres
      - PGPASSWORD=2700
      - PGPORT=${PG_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SESSION_DB_NUMBER=0
      - REDIS_SESSION_CASH_NUMBER=1
      - JWT_SECRET_WORD=${JWT_SECRET_WORD}
      - SESSION_EXPIRE_TIME=${SESSION_EXPIRE_TIME}
      - ACCESS_TOKEN_EXPIRE_TIME=${ACCESS_TOKEN_EXPIRE_TIME}
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: apple_pie_postgres
    build: ./postgres
    restart: unless-stopped
    volumes:
      - ./postgres/schema.sql:/app/schema.sql
    ports:
      - ${PG_PORT}:${PG_PORT} # только для GUI базы
    environment:
      - POSTGRES_PASSWORD=2700

  redis:
    container_name: apple_pie_redis
    build: ./redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} # только для GUI базы
    volumes:
      - ./redis/redis.conf:/app/redis.conf
