version: '3.1'

services:
  nginx:
    container_name: apple_pie_nginx
    build: ./nginx
    restart: unless-stopped
    ports:
        - '80:80'
    volumes:
        - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - root_server

  root_server:
    container_name: apple_pie_root_server
    build: ./root_server
    restart: unless-stopped
    volumes:
      - ./root_server/src:/app/src
    depends_on:
      - root_db

  root_db:
    container_name: apple_pie_root_db
    build: ./root_db
    restart: unless-stopped
    volumes:
      - ./root_db/schema.sql:/app/schema.sql
    ports:
      - '5432:5432' # только для GUI базы

  auth_server:
    container_name: apple_pie_auth_server
    build: ./auth_server
    restart: unless-stopped
    volumes:
      - ./auth_server/src:/app/src
