version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose.override.yaml
      service: postgres
    restart: on-failure:5

  redis:
    extends:
      file: docker-compose.override.yaml
      service: redis
    restart: on-failure:5

  client:
    extends:
      file: docker-compose.override.yaml
      service: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: on-failure:5

  server:
    extends:
      file: docker-compose.override.yaml
      service: server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: on-failure:5
    environment:
      - IS_DEV=true
      - APP_DOMAIN=http://apple-pie.fun
      - MAILING_ACCOUNT=apple_pie_test@outlook.com
      - MAILING_ACCOUNT_PASSWORD=apple_pie_2700
      - GOOGLE_OAUTH_ID=535551783086-ptn15am3ih5s790gq3fhiqd7ij2eg1nk.apps.googleusercontent.com
      - GOOGLE_OAUTH_KEY=07Dwh0gkfMz-lkesy4K7YxW8

  nginx:
    extends:
      file: docker-compose.override.yaml
      service: nginx
    restart: on-failure:5
