-- reset

DROP TABLE IF EXISTS users;

-- schema

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(20) UNIQUE NOT NULL,
    password CHARACTER VARYING(20) NOT NULL,
    email CHARACTER VARYING(30) UNIQUE,
    role INTEGER NOT NULL
);
